### ISSUE TITLE
Feature: Minimum output level

### ISSUE THREAD

**Issue by knweiss** [arthepsy/ssh-audit#2]
Feature request: Add an option to configure the **minimum output level**.

Then it would be possible to report e.g. only fails (`--level=fail`) or fails and warnings (`--level=warn`).

**Comment by arthepsy** [comment]
Although one can simply grep the results, I see how this can be useful. Will implement it, just have to rethink about command line arguments parsing (usually I would just use [click](http://click.pocoo.org/) module, but I don't want to add dependencies for this project).

**Comment by arthepsy** [comment]
@knweiss, I kind of implemented the feature, but wanted some input beforehand. Let's say level is set to fail. Then some sections (e.g., "host-key-algorithms") will be empty and have just the header. What do You think, - should they be shown or not shown at all? Also, I guess "general" section should be shown always.

**Comment by knweiss** [comment]
@arthepsy I think I would not to print headers of empty sections . For me, the idea of the level-mode is to trim the output down to the important, actionable issues. If there's no issue in the general section I wouldn't print it either.

(Imagine scanning a couple of hundreds machines in a network: The output should provide a compact list of all the issues at the requested level and skip the rest.)

What about not printing the headers at all in the level-mode? There are still the three letter prefixes at the beginning of the line.

**Comment by arthepsy** [comment]
Yes, I think it's a good idea to not print headers of empty sections, but that would leave empty lines between sections. I don't want to put so much weight on single argument, therefore, maybe something like `-c` (as in compact mode) could be used together with `--level`, which would also trim empty lines. Sounds reasonable?

You make a good point about having prefixes for each line. But I noticed that general section doesn't have them. There's either `[info]` or `[fail]` (which could happen only if SSH1 is enabled). Maybe I should add prefix for general section also, for all of this to work.

**Comment by knweiss** [comment]
Yes, this would be more consistent.

**Comment by arthepsy** [comment]
My guess is that You (using `--level`) would like each line to have prefix, but then currently one have to add `-v` to fill each line with prefix. I'm rethinking that `-c`/`--compact` isn't enough and maybe it it would be better to have `-b`/`--batch` (for batch/script parsing), i.e., which would imply compact output and also imply having `-v`.

Therefore, usage would be: `./ssh-audit.py -bl fail <host>`

Would that satisfy Your requirements, @knweiss?

P.S. I You have idea how to prefix general section to three-letters, that would be awesome, because I'm also adding security section (#4), which I will prefix with `(sec)` and/or `(cve)`.

**Comment by knweiss** [comment]
Sounds good.

**Comment by arthepsy** [comment]
@knweiss, could You check if everything is fine and dandy? (I pushed commit).

**Comment by knweiss** [comment]
Very nice, I like it. Thanks a lot!

**Comment by arthepsy** [comment]
:ok_hand:
